### PR TITLE
Explore version again

### LINKED ISSUE #705: Release name of the Android app has changed
Screenshot from 2023-07-17 08-21-33

Instead of our release name like _Ladybird 6.26-365_ I see the date there _2023-07-13_

### PR DESCRIPTION
**Pull request by dbnicholson**
Really make sure the version identifiers derived from the explore plugin actually work.

Fixes: https://github.com/endlessm/kolibri-explore-plugin/issues/705

### CODE REVIEW

**Comment by pwithnall** [comment]
LGTM. This explains why I didn’t hit this when I was testing the previous PR, as I was operating off an already-downloaded whl.

**Review by pwithnall — APPROVED** [review]
Go ahead and merge once CI passes

**Comment by dbnicholson** [comment]
Hmm, I just tried to build and got:

```
Traceback (most recent call last):
  File "/home/dan/src/kolibri/kolibri-installer-android/scripts/version.py", line 143, in <module>
    print(get_ek_version())
  File "/home/dan/src/kolibri/kolibri-installer-android/scripts/version.py", line 115, in get_ek_version
    explore_plugin_version(), kolibri_version(), android_version_indicator
  File "/home/dan/src/kolibri/kolibri-installer-android/scripts/version.py", line 40, in explore_plugin_version
    spec = importlib.util.spec_from_file_location(
AttributeError: module 'importlib' has no attribute 'util'
```

So, uh, hang on.

**Comment by dbnicholson** [comment]
Looking closer at [the last build](https://ci.endlessos.org/job/kolibri-installer-android/203/), that also happened on Jenkins.

**Review by pwithnall — APPROVED** [review]
Sure. `import importlib` worked fine for me locally, which is a bit confusing. Differences between different Python versions, perhaps? I’m on 3.11.

**Comment by dbnicholson** [comment]
> Sure. `import importlib` worked fine for me locally, which is a bit confusing. Differences between different Python versions, perhaps? I’m on 3.11.

Probably. Jenkins and I are using 3.9 from eos master. I was trying to see where this might have [changed](https://github.com/python/cpython/commits/main/Lib/importlib/__init__.py), but I couldn't figure it out. Anyways, it's good practice to import the full path you're going to use, IMO.

**Comment by dbnicholson** [comment]
The PR build seems to have done the right thing:

```
echo '{"versionCode": "650", "versionName": "Ladybird 6.30-650", "ekVersion": "6.30.0-0.16.0a18-11435b5"}' > dist/version.json
```

Merging.

**Pull request merged**
