### PR TITLE
Webview: Drop USB APIs relating to Welcome screen

### LINKED ISSUE #171: Stop using the welcome-screen USB APIs on Android
We have [Change the initial screen so it doesn't offer the USB option.](https://github.com/endlessm/kolibri-explore-plugin/issues/732)
So, we can drop USB API corresponding Android webview and dependent code.

### PR DESCRIPTION
**Pull request by starnight**
Since the commit ("Welcome: Drop USB/SD option from Welcome screen") of kolibri-explore-plugin [1] drops the USB option, Endless Key app removes corresponding USB APIs accordingly.

[1]: https://github.com/endlessm/kolibri-explore-plugin

Fixes: https://github.com/endlessm/kolibri-installer-android/issues/171

### CODE REVIEW

**Review by dbnicholson — CHANGES_REQUESTED** [review]
Looks good. There's also all the `kolibri_whitenoise` hacking that becomes unnecessary after this, but we can do that as a followup. I did a quick test run and it got to the download page.

I think you can delete everything to do with `android_utils.get_endless_key_uris`, `StartupState.USB_USER` and `KOLIBRI_CONTENT_FALLBACK_DIRS`.

**Comment by starnight** [comment]
Drop `get_endless_key_uris`, `USB_USER` and `KOLIBRI_CONTENT_FALLBACK_DIRS`.  Also, remove the WhiteNoise in the new commits.

**Review by dbnicholson — APPROVED** [review]
This looks good to me and ran correctly in my testing. I added one more revert to completely remove the `DocumentsProvider` support. We don't have any more use for that. @dylanmccall wanted to take a look at this, so I'm adding him as a reviewer.

**Review by dylanmccall — APPROVED** [review]
Yes, this all looks marvellous to me, too! I'll merge it :)

**Comment by starnight** [comment]
Tested by the comment https://github.com/endlessm/kolibri-installer-android/issues/171#issuecomment-1679940593

**Pull request merged**
