### PR TITLE
Logging improvements

### LINKED ISSUE #126: Improve logging
Logging works but there are several deficiencies.

1. Logs are forwarded to Android Log via a generic stderr converter in the pythonforandroid C code. This works, but all of the logs use the generic `python` tag and they're all logged at `INFO` priority.
2. Kolibri's logging configuration adds logging to the `logs/kolibri.txt` file, which is nice since they persist to disk, unlike the Android logs, which are in memory. However, this is only applied once Kolibri is initialized, so any early logs are not sent to disk.
3. Exceptions are logged to stderr, which ends up in the Android log via the above pythonforandroid mechanism. If they were logged with python logging, they'd be better formatted and recorded into the persisted logging file.

### PR DESCRIPTION
**Pull request by dbnicholson**
This improves the logging (considerably, IMO) by providing a logging handler to send messages directly to Android Log and completely overriding the Kolibri logging configuration so we can set it up the way we want.

Fixes #126.

### CODE REVIEW

**Review by dylanmccall — CHANGES_REQUESTED** [review]
I like this, and I have no objections here, although this is a pretty substantial change so could we add a Phabricator task for it and tweak the commits accordingly?

**Comment by wjt** [comment]
I instead tagged it onto the new GitHub project :)

**Comment by dbnicholson** [comment]
I added an issue here as suggested by @erikos - #126. I also added one more commit after I started playing with crashlytics and noticed that it would be better to record the exception with `logging`.

**Comment by dbnicholson** [comment]
Whoops. Updated the last commit to remove the synthetic testing exception I was using.

**Comment by wjt** [comment]
@dylanmccall is this good to go with the "Goodbye cruel world" removed?

**Pull request merged**
