### PR TITLE
Jenkins: Change Kolibri WHL URL to v0.16.0-alpha18

### LINKED ISSUE #156: ChromeOS: Bump Kolibri to 0.16-alpha18
It has been released: https://github.com/learningequality/kolibri/releases/tag/v0.16.0-alpha18

### PR DESCRIPTION
**Pull request by manuq**
Resolves #156

### CODE REVIEW

**Comment by pwithnall** [comment]
Currently smoketesting this on my ChromeOS device

**Comment by pwithnall** [comment]
Testing the apk generated by Jenkins, I can select a pack to download, but Kolibri then shows the loading screen forever (I’ve waited 30 minutes so far). The animation continues to play, so the app isn’t frozen, but it doesn’t appear to be managing to download things.

The only relevant error message I can see on `adb logcat` is:
```
EKWebConsole: Uncaught SyntaxError: Unexpected token ? -- Source: http://127.0.0.1:37257/static/kolibri_explore_plugin.app/kolibri_explore_plugin.app-6.24.0.js
```

Does that look like a smoking gun, or is it to be expected from the app? Unfortunately it didn’t print a line number.

**Comment by wjt** [comment]
Yes, that does look like a smoking gun.

I would suggest:

1. Erase the app data
2. Launch the app
3. Before picking a content pack, follow the instructions at https://phabricator.endlessm.com/w/apps/endlesskey/chromebook/#manage-kolibri-content-i to attach the Chrome web inspector (on your laptop) to the app's webviews (there are 2!)
4. Now go through the onboarding flow until you (hopefully) trigger the SyntaxError and (hopefully) get a better backtrace

**Comment by pwithnall** [comment]
After some fiddling about, this is hopefully fixed by https://github.com/endlessm/kolibri-explore-plugin/pull/693.

---

1. I installed the apk using [this guide](https://www.howtogeek.com/752759/how-to-sideload-apks-on-a-chromebook-without-developer-mode/)
2. As Will suggested, I followed the [instructions](https://phabricator.endlessm.com/w/apps/endlesskey/chromebook/#manage-kolibri-content-i) to get a Chrome web inspector working, using the Chrome on my ChromeOS machine
3. That pointed to line 2, offset 1591085 of `kolibri_explore_plugin.app-6.24.0.js`, which is around `MediaTypeVerbs[this.kind]??`
4. I used `adb forward` to forward the Kolibri web port from my ChromeOS machine, and accessed it using Chrome on my main laptop; to my surprise, the content pack download continued and the page worked fine. It did allow me to download and un-minify the JavaScript file, and trace it down to `EkPlayButton.vue`
5. `adb shell dumpsys package com.google.android.webview | grep versionName` gives 68.0.3440.91 on my ChromeOS machine, whereas I’m using Chromium 87.0.4280.66 on my main laptop; this explains the difference in being able to handle the nullish coalescing operator

**Comment by pwithnall** [comment]
I [ran the Jenkins build for the apk again](https://ci.endlessos.org/job/kolibri-installer-android-pr/474/) to get the new kolibri-explore-plugin release, tested it, and now get `Uncaught SyntaxError: Unexpected token .`.

Unfortunately Chrome DevTools don’t want to un-minify the JS this time, so I can’t pinpoint where the problem is. Accessing Kolibri remotely with my modern Chromium on my main laptop loads the page fine, though, so it’s definitely another instance of the outdated WebView causing problems.

Looks like we need a more systematic fix. Filed https://github.com/endlessm/kolibri-installer-android/issues/159.

It’s likely that Kolibri 0.16.0-alpha18 works fine, so perhaps it would make sense for someone with a more up-to-date WebView to quickly smoketest it, and then we can unblock and merge this PR, and work on the outdated WebView thing in a separate issue (https://github.com/endlessm/kolibri-installer-android/issues/159)?

**Comment by wjt** [comment]
That Jenkins job also crashed with java.lang.NullPointerException. Could
you open an issue about that?

**Comment by wjt** [comment]
I am testing the APK from that PR on my Chromebook…

**Comment by wjt** [comment]
The app crashed during the transition from "choose your starter pack" to downloading the pack, and again while downloading the pack:

```
07-07 15:16:54.107   365  1038 I ActivityManager: Process com.google.android.webview:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:0 (pid 4581) has died: fg  BTOP
07-07 15:16:54.109   365   391 W libprocessgroup: Failed to open process cgroup uid 99001 pid 4581: Permission denied
07-07 15:16:54.109   365   391 E libprocessgroup: Error encountered killing process cgroup uid 99001 pid 4581: Permission denied
07-07 15:16:54.110   365  1038 W ActivityManager: Scheduling restart of crashed service org.endlessos.Key/org.chromium.content.app.SandboxedProcessService0:0 in 1000ms for connection
07-07 15:16:54.115   365  1038 D CompatibilityChangeReporter: Compat change id reported: 136274596; UID 10082; state: ENABLED
07-07 15:16:54.120   553   553 I Zygote  : Process 4581 exited due to signal 9 (Killed)
07-07 15:16:54.139  4531  4577 W cr_ChildProcessConn: onServiceDisconnected (crash or killed by oom): pid=4581 bindings:W  S
07-07 15:16:54.157  4531  4531 E chromium: [ERROR:aw_browser_terminator.cc(156)] Renderer process (4581) crash detected (code -1).
07-07 15:16:54.160  4531  4531 E chromium: [ERROR:aw_browser_terminator.cc(112)] Render process (4581) kill (OOM or update) wasn't handed by all associated webviews, killing application.
07-07 15:16:54.930   365   429 W InputDispatcher: channel '1ab64c1 org.endlessos.Key/org.kivy.android.PythonActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
07-07 15:16:54.931   365   429 E InputDispatcher: channel '1ab64c1 org.endlessos.Key/org.kivy.android.PythonActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
07-07 15:16:54.932   194   194 I Zygote  : Process 4531 exited due to signal 9 (Killed)
07-07 15:16:54.935   365  1038 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ TRACK_DEFAULT id=51, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10082 AdministratorUids: [] RequestorUid: 10082 RequestorPackageName: org.endlessos.Key] ], android.os.BinderProxy@6dcb907)
07-07 15:16:54.940   365  3102 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=52, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&FOREGROUND Uid: 10082 AdministratorUids: [] RequestorUid: 10082 RequestorPackageName: org.endlessos.Key] ], android.os.BinderProxy@ec51a34)
07-07 15:16:54.940   365   445 D ConnectivityService: releasing NetworkRequest [ TRACK_DEFAULT id=51, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10082 AdministratorUids: [] RequestorUid: 10082 RequestorPackageName: org.endlessos.Key] ] (release request)
```

seems to be the offending section. I'll check if it also happens with the released version…

**Comment by pwithnall** [comment]
> That Jenkins job also crashed with java.lang.NullPointerException. Could you open an issue about that?

I was assuming that was because I went a non-standard way and started it via ‘Replay’, and that it wasn’t worth reporting unless it’s reproducible via the normal route of triggering it from GitHub via a PR. The dereference appears to be in the `post` steps, possibly `buildDescription("UPLOAD=${params.UPLOAD}")`, so it’s harmless in terms of generating the apk successfully.

**Comment by dbnicholson** [comment]
Is this OK to be merged? I feel like the issues hit here are independent of kolibri and the android installer is no longer buildable since the kolibri 0.16.0a15 wheel no longer exists on github.

**Pull request merged**
