### PR TITLE
p4a: Add metadata to maximize window

### PR DESCRIPTION
**Pull request by manuq**
https://phabricator.endlessm.com/T33607

### CODE REVIEW

**Comment by manuq** [comment]
I expect jenkins to fail as this depends on https://github.com/endlessm/python-for-android/pull/5 being merged and pinned in the Makefile.

**Review by dbnicholson — APPROVED** [review]
:+1:

**Comment by dbnicholson** [comment]
Hmm, jenkins failed saying p4a was missing the option, but that seems wrong. Let's try that again.

**Comment by dbnicholson** [comment]
retest this please

**Comment by dbnicholson** [comment]
retest this please

**Comment by dbnicholson** [comment]
Ohh... it's because `build.py` is loaded from the p4a cached dist directory. I think we might really want to stop any p4a caching in jenkins. It's too broken.

**Comment by dbnicholson** [comment]
retest this please

**Comment by dbnicholson** [comment]
Yep, it succeeded after I manually deleted the docker volume being used as the p4a cache.

**Comment by dbnicholson** [comment]
Can we look at #39 (the last commit in particular) before merging this so that the normal build doesn't break reusing the wrong p4a?

**Comment by dbnicholson** [comment]
#39 got merged, so taking this now.

**Pull request merged**
