### PR TITLE
WIP

### PR DESCRIPTION
**Pull request by manuq**
https://phabricator.endlessm.com/T33793

### CODE REVIEW

**Review by dbnicholson — COMMENTED** [review]
It looks like you took the code from LE's develop branch, but I don't see the commits. Is that intentional?

Also, can you update the `Jenkinsfile` so it uses a correct kolibri wheel?

**Comment by manuq** [comment]
> It looks like you took the code from LE's develop branch, but I don't see the commits. Is that intentional?

Yes, the LE commits don't apply directly into our `main.py`. Also their git history is not that clean. Example: https://github.com/learningequality/kolibri-installer-android/commit/688583d3100b45b089d553921add057abdfa0226. So I preferred to copy/paste the current code.

> Also, can you update the `Jenkinsfile` so it uses a correct kolibri wheel?

OK, I was waiting for a new alpha release but even that won't give us a wheel file in PyPi. So I think we can `wget` it from their buildkite.com. I will have to adapt the Makefile to do:
```
wget -O kolibri-0.16.0.dev0+git.20220902161333-py2.py3-none-any.whl https://buildkite.com/organizations/learningequality/pipelines/kolibri-python-package/builds/6198/jobs/0182fefa-da30-4683-a144-e7a7c0d3067c/artifacts/0182ff0f-a9e4-4384-bf26-d941243db21c
```

**Comment by manuq** [comment]
Converting to draft until we have a kolibri-explore-plugin for 0.16 in PyPi.

**Comment by dbnicholson** [comment]
> > It looks like you took the code from LE's develop branch, but I don't see the commits. Is that intentional?
> 
> Yes, the LE commits don't apply directly into our `main.py`. Also their git history is not that clean. Example: [learningequality@688583d](https://github.com/learningequality/kolibri-installer-android/commit/688583d3100b45b089d553921add057abdfa0226). So I preferred to copy/paste the current code.

Sure, but once you do that we effectively decouple our history from theirs. Is that the intention? Every upstream is going to have unclean history sometimes, but if you merge or rebase the final commit I don't think it really matters.

**Comment by manuq** [comment]
@dbnicholson ok, I will try merging / rebasing and fixing conflicts today. My worry is that we already have decoupled our history from theirs a while ago. Maybe another option is to start over again from their main branch and try to move our `main.py` customizations to a separate Python module.

**Comment by dbnicholson** [comment]
> @dbnicholson ok, I will try merging / rebasing and fixing conflicts today. My worry is that we already have decoupled our history from theirs a while ago. Maybe another option is to start over again from their main branch and try to move our `main.py` customizations to a separate Python module.

That's fair. Maybe in the interest of time let's just keep what you have right now. We can always pull it back together later.

**Comment by dbnicholson** [comment]
retest this please

**Pull request merged**
