### PR TITLE
Rename welcomeScreen to loadingScreen

### PR DESCRIPTION
**Pull request by manuq**
Helps https://github.com/endlessm/kolibri-explore-plugin/issues/748

### CODE REVIEW

**Comment by dbnicholson** [comment]
Marking this as a draft so it's not merged until an explore plugin release is made with the changes.

**Review by dbnicholson — APPROVED** [review]
I haven't tested this, but it looks appropriate to me.

**Comment by dbnicholson** [comment]
I tested this locally now that 7.0.0 is released. I had to change the requirement in the `.p4a` file, but I think this is ready now.

**Review by starnight — CHANGES_REQUESTED** [review]
Th CI builds failed.  The **clean** target in Makefile depends on `clean-welcomeScreen`.  But, `clean-welcomeScreen` has been changed to `clean-loadingScreen`.  :)

**Comment by dbnicholson** [comment]
Ah, right. I did that change in between.

**Comment by dbnicholson** [comment]
The build succeeded now. Merging.

**Pull request merged**
