### PR TITLE
Endless Key USB with Storage Access Framework

### PR DESCRIPTION
**Pull request by dbnicholson**
Still working through this, but I'm getting closer. So far this brings up a dialog for the user to choose the `KOLIBRI_DATA` directory and give access to it. Then the database is copied to internal storage.

The remaining part is getting access to the content from `CONTENT_FALLBACK_DIRS` to work through Storage Access Framework. I've got the basic file access patterns worked out, but mangling the custom `Whitenoise` classes used in Kolibri is kind of nasty.

https://phabricator.endlessm.com/T33662

### CODE REVIEW

**Comment by dbnicholson** [comment]
retest this please

**Comment by dbnicholson** [comment]
I changed the PR to not use androidx, which was involved in the previous build failure. I think this is ready for review now. I'm happy with the changes except that the code could use more comments and doc strings. I may make one more pass through for that.

**Review by danigm — APPROVED** [review]
This looks good to me. The whitenoise monkeypatching is something we can think about upstreaming and use depending on the platform detection, but for now I think it's okay to keep this monkey patching function.

**Comment by dbnicholson** [comment]
I added a few commits to improve selection of the EK USB. The `KOLIBRI_DATA` folder should be pre-selected, and some toasts will be shown instructing the user on what to do. The toasts aren't that great, but I think it's the best we can do with the file picker.

Also, if you select the wrong folder or cancel (by going back out of the file picker), it will still continue on using internal storage. It would be better to put you back at the "Insert your EK USB" page instead, but I need a little help from @danigm with that to understand the webview interaction.

I think this is good for now and will allow us to carry on with the app review while we iterate on the loading UX.

**Comment by dbnicholson** [comment]
I'm going to merge this now and we can tweak more as needed.

**Comment by danigm** [comment]
> I added a few commits to improve selection of the EK USB. The `KOLIBRI_DATA` folder should be pre-selected, and some toasts will be shown instructing the user on what to do. The toasts aren't that great, but I think it's the best we can do with the file picker.
> 
> Also, if you select the wrong folder or cancel (by going back out of the file picker), it will still continue on using internal storage. It would be better to put you back at the "Insert your EK USB" page instead, but I need a little help from @danigm with that to understand the webview interaction.
> 
> I think this is good for now and will allow us to carry on with the app review while we iterate on the loading UX.

To show again the USB screen we just need to call a javascript function in the [loading screen](https://github.com/endlessm/kolibri-installer-android/blob/develop/src/main.py#L91).

I think that we can detect [here](https://github.com/endlessm/kolibri-installer-android/blob/a0a07e57d963f7640a3d75bb9a11836317713ec2/src/main.py#L134-L141) that the selected folder is not correct and we can call

```
            PythonActivity.mWebView.evaluateJavascript("show_endless_key()", None)
```

instead of calling `start_kolibri`.

**Comment by dbnicholson** [comment]
> I think that we can detect [here](https://github.com/endlessm/kolibri-installer-android/blob/a0a07e57d963f7640a3d75bb9a11836317713ec2/src/main.py#L134-L141) that the selected folder is not correct and we can call
> 
> ```
>             PythonActivity.mWebView.evaluateJavascript("show_endless_key()", None)
> ```
> 
> instead of calling `start_kolibri`.

I tried doing exactly that, but you get an error that it needs to be called from the webview thread, not the python thread. I think the `FullScreen` class will need a bit of refactoring so that it exposes a method to run the desired javascript directly or some other method that tells it to go run the `loadWithUsb` javascript interface.

**Pull request merged**
